config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do

    get :sign_in, to: 'cookies#sign_in'
    post :to_sign_in, to: 'cookies#to_sign_in'
    delete :sign_out, to: 'cookies#sign_out'
    get :forget_password, to: 'cookies#forget_password'
    put :change_password, to: 'cookies#change_password'
    root 'dashboard#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  include KlassConcern
  include XlsxConcern

  acts_as_paranoid # 假删除
end

app/models/concerns/klass_concern.rb
# frozen_string_literal: true

module KlassConcern
  extend ActiveSupport::Concern

  included do
    before_create :generate_uuid
    def generate_uuid
      uuid = UUID.new
      self_slug = uuid.generate
      generate_uuid if self.class.find_by_slug(self_slug).present?
      self.slug = self_slug
    end
  end

  module ClassMethods
    # 获取分页的内容
    def page_statistical(instance_objects)
      if instance_objects.respond_to?(:total_count)
        {
          total_count: instance_objects.total_count,
          current_page: instance_objects.current_page,
          total_pages: instance_objects.total_pages
        }
      end
    end
  end
end

app/models/concerns/xlsx_concern.rb
require 'write_xlsx'

module XlsxConcern
  extend ActiveSupport::Concern

  included do
  end

  module ClassMethods
    # 返回文件路径
    def export_xlsx(name: 'table')
      path = Rails.root.join('tmp').to_path + "/#{name}.xlsx"
      generate_xlsx(path)
      path
    end

    # 生成xlsx表
    def generate_xlsx(path)
      xlsx_file = WriteXLSX.new(path)
      xlsx_sheet = xlsx_file.add_worksheet
      attribute_names = self.attribute_names
      attribute_names.each_with_index do |name, index|
        xlsx_sheet.write(0, index, human_attribute_name(name))
      end
      all.each_with_index do |user, index|
        attribute_names.each_with_index do |name, name_index|
          xlsx_sheet.write(index + 1, name_index, user[name])
        end
      end
      xlsx_file.close
    end
  end
end

app/models/school.rb
class School < ApplicationRecord
  extend FriendlyId
  friendly_id :uuid, use: %i[slugged finders]

  has_many :users, dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_token
  has_secure_password
  extend FriendlyId
  extend Enumerize
  extend ActiveModel::Naming
  
  enumerize :kind, in: { admin: 0, normal: 1 }, default: 1, predicates: true, scope: true, i18n_scope: 'kind'

  friendly_id :slug, use: %i[slugged finders]

  belongs_to :school, counter_cache: true
end

app/controllers/admin/application_controller.rb
# frozen_string_literal: true
class Admin::ApplicationController < ActionController::Base
  layout 'admin/layouts/application'

  before_action :had_sign_in?

  private

  def had_sign_in?
    redirect_to admin_sign_in_path if current_admin.blank?
  end
  
  def current_admin
    @current_admin ||= User.find_by_token(cookies[:token])
  end

  helper_method :current_admin
end

app/controllers/admin/cookies_controller.rb
# frozen_string_literal: true

class Admin::CookiesController < Admin::ApplicationController
  layout 'admin/layouts/cookies.html.erb', only: %i[sign_in forget_password]
  skip_before_action :had_sign_in?, only: %i[sign_in to_sign_in forget_password change_password]

  def sign_in; end

  def to_sign_in
    if params[:account].present? && params[:password].present?
      @user = User.find_by_account(params[:account])
      if @user.present?
        if @user.authenticate(params[:password])
          expires = 1.hours
          expires = 7.days if params[:remenber].present?
          cookies[:token] = { value: @user.token, expires: expires }
          flash[:notice] = '登录成功！'
          redirect_to admin_root_path
        else
          flash[:alert] = '请填写正确的密码！'
          redirect_to :admin_sign_in
        end
      else
        flash[:alert] = '请填写正确的用户名！'
        redirect_to :admin_sign_in
      end
    else
      flash[:alert] = '请填写正确的用户名和密码！'
      redirect_to :admin_sign_in
    end
  end

  def forget_password; end

  def change_password
    @user = User.find_by_account(params[:account])
    if @user.blank?
      flash[:alert] = '请填写正确的用户账号！'
      redirect_to admin_forget_password_path
    end
    if @user.mobile != params[:mobile]
      flash[:alert] = '请填写正确的手机号码！'
      redirect_to admin_forget_password_path
    end
    @user.password = params[:password]
    if @user.save
      flash[:notice] = '密码修改成功，请登录！'
      redirect_to admin_sign_in_path
    else
      flash[:alert] = '修改失败，请重试！'
      redirect_to admin_forget_password_path
    end
  end

  def sign_out
    cookies.delete('token')
    redirect_to admin_sign_in_path
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
end

app/helpers/admin/cookies_helper.rb
module Admin::CookiesHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/application/_admin_left_bar.html.erb
<div class="admin-left-bar">
</div>

app/views/admin/application/_admin_right_footer.html.erb
<nav class="navbar navbar-light bg-light justify-content-center admin-right-footer">
  <span class="navbar-text">
    Navbar text with an inline element
  </span>
</nav>

app/views/admin/application/_admin_right_header.html.erb
<nav class="navbar navbar-light bg-light justify-content-between admin-right-header">
  <span class="navbar-text">
    Navbar text with an inline element
  </span>
  <div class="btn-group">
    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= current_admin.realname %>
    </a>
    <div class="dropdown-menu dropdown-menu-right">
      <a class="dropdown-item" href="#">修改密码</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="<%= admin_sign_out_path %>" data-method="delete">退出</a>
    </div>
  </div>
</nav>

app/views/admin/cookies/forget_password.html.erb
<div class="row align-items-center justify-content-center cookies-forget-password">
  <div class="col-4">
    <%= form_tag admin_change_password_path, method: :put, id: 'forget-password-form' do %>
      <div class="error-tips <%= flash[:alert].present? ? 'show' : 'hide' %>">
        <%= flash[:alert] %>
      </div>
      <div class="form-row">
        <div class="col-12">
          <label for="account">用户账号：</label>
          <%= text_field_tag :account, '', class: 'form-control', placeholder: '请输入用户账号' %>
        </div>
      </div>
      <div class="form-row">
        <div class="col-12">
          <label for="mobile">手机号码:</label>
          <%= password_field_tag :mobile, '', class: 'form-control', placeholder: '请输入手机号码' %>
        </div>
      </div>
      <div class="form-row">
        <div class="col-12">
          <label for="password">密码:</label>
          <%= password_field_tag :password, '', class: 'form-control', placeholder: '请输入密码' %>
        </div>
      </div>
      <div class="form-row">
        <div class="col-12">
          <label for="password_confirmation">确认密码:</label>
          <%= password_field_tag :password_confirmation, '', class: 'form-control', placeholder: '请输入确认密码' %>
        </div>
      </div>
      <div class="form-row">
        <div class="col-12">
          <label for="mobile">验证码:</label>
          <%= rucaptcha_input_tag(class: 'form-control', placeholder: '请输入验证码') %>
          <%= rucaptcha_image_tag(alt: 'Captcha', class: 'captcha') %>
        </div>
      </div>
      <button class="btn btn-primary btn-block" id="sign_up_form_submit" type="submit">立即修改密码</button>
    <% end %>
  </div>
</div>

app/views/admin/cookies/sign_in.html.erb
<div class="row align-items-center justify-content-center cookies-sign-in">
  <div class="col-4">
    <%= form_tag admin_to_sign_in_path, method: :post, id: 'sign-in-form' do %>
      <div class="error-tips <%= flash[:alert].present? ? 'show' : 'hide' %>">
        <%= flash[:alert] %>
      </div>
      <div class="form-row">
        <div class="col-12">
          <label for="account">用户账号：</label>
          <%= text_field_tag :account, '', class: 'form-control', placeholder: '请输入用户账号' %>
        </div>
      </div>
      <div class="form-row">
        <div class="col-12">
          <label for="password">密码:</label>
          <%= password_field_tag :password, '', class: 'form-control', placeholder: '请输入密码' %>
        </div>
      </div>
      <div class="form-group d-flex justify-content-between align-items-center">
        <div class="form-check">
          <input type="checkbox" class="form-check-input" id="remenber" name="remenber">
          <label class="form-check-label" for="remenber">记住我！</label>
        </div>
        <a href="<%= admin_forget_password_path %>">忘记密码？</a>
      </div>
      <button class="btn btn-primary btn-block" id="sign_up_form_submit" type="submit">登录</button>
    <% end %>
  </div>
</div>

app/views/admin/dashboard/index.html.erb
<h1>Admin::Dashboard#index</h1>
<p>Find me in app/views/admin/dashboard/index.html.erb</p>

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render partial: 'admin_left_bar' %>
    <div class="admin-right-content">
      <%= render partial: 'admin_right_header' %>
      <div class="admin-right-main">
        <%= yield %>
      </div>
      <%= render partial: 'admin_right_footer' %>
    </div>
  </body>
</html>

app/views/admin/layouts/cookies.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>SchoolOa</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>

</html>